#!/bin/bash
set -e

# Step 0: Check if main.py exists before uv init
MAIN_EXISTS=false
[ -f main.py ] && MAIN_EXISTS=true

# Step 1: Run uv init 
uv init

# Extract project name generated by uv init or fall back to directory name
NEW_PROJECT_NAME=$(grep -m 1 '^name = ' pyproject.toml | sed -E 's/name = "(.*)"/\1/' || echo "")
if [ -z "$NEW_PROJECT_NAME" ]; then
    NEW_PROJECT_NAME=$(basename "$PWD")
fi

# Step 2: Remove uv init generated extras (.python-version, main.py if created)
rm -f .python-version
if [ "$MAIN_EXISTS" = false ] && [ -f main.py ]; then
    rm -f main.py
    echo "Removed uv init generated main.py"
fi

# Step 3: Pull the template project structure
TEMPLATE_SOURCE="${TEMPLATE_URL:-https://github.com/sglbl/sg_project_template.git}"
if [ -d "$TEMPLATE_SOURCE" ]; then
    mkdir -p temp_template
    cp -R "$TEMPLATE_SOURCE/." temp_template/
else
    git clone --depth=1 "$TEMPLATE_SOURCE" temp_template
fi

# Step 4: Copy directories safely (only if they don't exist)
for dir in .vscode data docs notebooks src tests docker .agents; do
    [ ! -d "$dir" ] && [ -d "temp_template/$dir" ] && cp -r "temp_template/$dir" "$dir"
done

# Step 5: Copy template's full .gitignore (overwrites uv init default)
cp temp_template/.gitignore .gitignore

# Copy compose.yaml only if it doesn't exist
[ ! -f compose.yaml ] && [ -f temp_template/compose.yaml ] && cp temp_template/compose.yaml compose.yaml

# Copy executable wrapper script
[ -f temp_template/run ] && cp temp_template/run run && chmod +x run

# Copy README.md if missing or empty
if [ ! -s README.md ]; then
    [ -f temp_template/README.md ] && cp temp_template/README.md README.md
fi

# Step 6: Use template's full pyproject.toml with the new project name
if [ -f temp_template/pyproject.toml ]; then
    sed "s/name = \"sg-project-template\"/name = \"$NEW_PROJECT_NAME\"/" temp_template/pyproject.toml > pyproject.toml
fi

# Step 7: Clean up temporary template files
rm -rf temp_template
rm -rf data/example_inputs/

# Step 8: Sync dependencies
uv sync

echo "UV project '$NEW_PROJECT_NAME' initialized successfully with template .gitignore and pyproject.toml!"

# If you want to run locally:
# mkdir -p ~/codes/example && cd ~/codes/example && TEMPLATE_URL="$HOME/codes/sg_project_template" bash ~/codes/sg_project_template/data/example_inputs/setup_template_for_uv.sh