name: sgproject

services:
  ui:
    build: 
      context: .
      dockerfile: docker/ui.Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8501:8501

  marimo:
    build:
      context: .
      dockerfile: docker/marimo.Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 2719:2718
