name: sgproject

services:
  ui:
    build: 
      context: .
      dockerfile: docker/ui.Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - 8501:8501

  marimo:
    build:
      context: .
      dockerfile: docker/marimo.Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 2719:2718

  api:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    command: python -m src.main api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DB_HOST=postgres

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri postgresql://postgres:postgres@postgres:5432/mlflow --default-artifact-root s3://mlflow-artifacts/ --host 0.0.0.0

  # High-Performance Rust S3 Object Storage Service (RustFS / Garage)
  rustfs:
    image: dxflrs/garage:v1.0.0
    container_name: rustfs_storage_server
    ports:
      - "9000:3900"
    volumes:
      - ./data/rustfs_storage/meta:/var/lib/garage/meta
      - ./data/rustfs_storage/data:/var/lib/garage/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"