[project]
name = "sg-project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate==0.33.0",
    "bitsandbytes==0.43.3",
    "fastapi==0.109.0",
    "gradio==4.37.2",
    "loguru>=0.7.2",
    "matplotlib>=3.9.2",
    "numpy==1.26.3",
    "pandas==2.2.0",
    "pillow==10.4.0",
    "psycopg2-binary==2.9.9",
    "pydantic-core==2.20.1",
    "pydantic==2.8.2",
    "python-dotenv==1.0.1",
]
