[project]
name = "sg-project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "gradio>=5.6.0",
    "loguru>=0.7.2",
    "numpy==2.1.3",
    "opencv-python>=4.10.0.84",
    "pydantic==2.8.2",
    "python-dotenv==1.0.1",
    "torch==2.5.1+cpu",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "pyproject-toml>=0.0.12",
    "pytest>=8.3.3",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"
