services:
  sgproject:
    image: sgproject:latest
    # build: 
    #   context: ..
    #   dockerfile: docker/build.Dockerfile
    # pull_policy: build
    restart: unless-stopped
    # env_file:
    #   - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      # - OPENAI_API_KEY=${OPENAI_API_KEY:-12345}
    ports:
      - 11004:8000
    labels:
      - homepage.group=Prod
      - homepage.name=Digit
      - homepage.icon=https://moracabanas.github.io/deduce-assets/logo-signature.png
      - homepage.href=https://sgproject.deducedata.solutions/?__theme=dark
      - homepage.ping=https://sgproject.deducedata.solutions/
      - homepage.description=Digit Classification Project
    # volumes:
    #   - pped_data:/app/data

# networks:
#   default:
#     name: supabase_default
#     external: true

# volumes:
#   pped_data: